version: '3'

services:
  postgres9:
    image: postgres:9.6
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: django_rest_api
      POSTGRES_USER: django
      POSTGRES_PASSWORD: admin
